[package]
name = "ch1"
version = "0.1.0"
edition = "2024"

[dependencies]
tg-sbi = { version = "0.1.0-preview.1", features = ["nobios"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
